# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Toolchain Properties
minecraft_version=26.1
fabric_loader_version=0.18.4
loom_version=1.15-SNAPSHOT
forge_version=62.0.2
neoforge_version=26.1.0.1-beta

# Mod Properties
mod_version=26.1-v2.19.0
maven_group=com.aizistral.nochatreports
archives_base_name=NoChatReports-FABRIC
mod_id=nochatreports
mod_name=No Chat Reports
mod_url=https://www.curseforge.com/minecraft/mc-mods/no-chat-reports
issue_tracker_url=https://github.com/Aizistral-Studios/No-Chat-Reports/issues
mod_author=Aizistral
mod_description=Strips cryptographic signatures from player messages, making it impossible to track and associate them with your Mojang/Microsoft account, as well as use Player Chat Reporting feature.
mod_icon=assets/nochatreports/textures/misc/ncr_logo.png
mod_license=WTFPL

# Dependencies
fabric_version=0.144.3+26.1
mod_menu_version=18.0.0-alpha.8
cloth_config_version=26.1.154

# Dependencies in mods.toml
dep_forge=[62,)
dep_neoforge=[26.1.0.1-beta,)
dep_minecraft=[26.1,)

# Publishing
curse_id=634062
version_type=release

#Contributors
contributor_0=Madis0 (aka robotkoer)
