# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Toolchain Properties
minecraft_version=26.2
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT
forge_version=65.0.0
neoforge_version=26.2.0.6-beta

# Mod Properties
mod_version=26.2-v2.20.0
maven_group=com.aizistral.nochatreports
archives_base_name=NoChatReports-FABRIC
mod_id=nochatreports
mod_name=No Chat Reports
mod_url=https://www.curseforge.com/minecraft/mc-mods/no-chat-reports
issue_tracker_url=https://github.com/Aizistral-Studios/No-Chat-Reports/issues
mod_author=Aizistral
mod_description=Strips cryptographic signatures from player messages, making it impossible to track and associate them with your Mojang/Microsoft account, as well as use Player Chat Reporting feature.
mod_icon=assets/nochatreports/textures/misc/ncr_logo.png
mod_license=WTFPL

# Dependencies
fabric_version=0.152.2+26.2
mod_menu_version=20.0.0-beta.3
cloth_config_version=26.2.155

# Dependencies in mods.toml
dep_forge=[65,)
dep_neoforge=[26.2.0.6-beta,)
dep_minecraft=[26.2,)

# Publishing
curse_id=634062
version_type=release

#Contributors
contributor_0=Madis0 (aka robotkoer)
