pluginManagement {
    repositories {
        maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
        maven { url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
        gradlePluginPortal {
			content {
				includeGroup "com.modrinth.minotaur"
				includeGroup "net.darkhax.curseforgegradle"
				includeGroup "net.minecraftforge.gradle"
				includeGroup "net.minecraftforge"
				includeGroup "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext"
			}
        }
    }
}

rootProject.name = 'No-Chat-Reports'
include('forge')
project(":forge").name = "Forge"
include('neoforge')
project(":neoforge").name = "NeoForge"