name: Bug Report
labels:
  - bug
assignees:
  - Aizistral
description: Report a bug
body:
  - type: dropdown
    id: modloader
    attributes:
      label: Modloader
      options:
        - Forge
        - Fabric
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: eg. 1.19.1
    validations:
      required: true
  - type: input
    id: modloader-version
    attributes:
      label: Modloader Version
      description: |
        List the version of the modloader you are using.
        If on Fabric, post the versions of both Fabric Loader and Fabric API.
      placeholder: "eg. Forge: 36.2.9 / Fabric: Loader 0.10.6 + API 0.42.1"
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: No Chat Reports Version
      placeholder: eg. 1.19.1-v1.8.2
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Modpack Info
      description: |
        If playing a modpack, post the link to it!
  - type: input
    attributes:
      label: "The latest.log file"
      description: "Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug Description
      placeholder: A description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. First step
        2. Second step
        3. etc...
  - type: textarea
    attributes:
      label: Other information
      description: Any other relevant information that is related to this issue, such as other mods and their versions.