name: Bug Report
labels:
  - bug
assignees:
  - Aizistral
description: Report a bug
body:
  - type: dropdown
    id: modloader
    attributes:
      label: Modloader
      options:
        - Forge
        - Fabric
        - Quilt
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: eg. 1.19.2
    validations:
      required: true
  - type: input
    id: modloader-version
    attributes:
      label: Modloader Version
      description: |
        List the version of the modloader you are using.
        If on Fabric - also specify version of Fabric API. If you don't have it installed separately - specify "Bundled API".
      placeholder: "eg. Forge: 43.1.1 / Fabric: Loader 0.14.10 + API 0.64.0"
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: No Chat Reports Version
      placeholder: eg. 1.19.2-v1.13.11
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Modpack Info
      description: |
        If playing a modpack, post the link to it. Leave empty otherwise.
  - type: input
    attributes:
      label: "The latest.log File"
      description: |
        Please use a paste site such as [mclogs](https://mclo.gs)/[gist](https://gist.github.com/)/[pastebin](https://pastebin.com/)/etc. Leave empty if log is not relevant.
  - type: textarea
    attributes:
      label: Bug Description
      placeholder: A description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Describe exact steps necessary to reproduce this bug. Leave empty if description above is self-explanatory.
      placeholder: |
        1. First step
        2. Second step
        3. etc...
  - type: textarea
    attributes:
      label: Other Information
      description: |
        Any other relevant information that is related to this issue, such as other mods and their versions. Leave empty if there is none.
